### ISSUE TITLE
Create Bootnodes & ENR

### ISSUE THREAD

**Issue by avenbreaks** [ethpandaops/ethereum-genesis-generator#20]
I see in values.env there is 

`export BEACON_STATIC_ENR= `

and what I understand before getting enr must have genesis.json and initialize it with datadir. or how can I get the bootnode so that it can be entered into values.env?

i made my own public blockchain sir.

**Comment by parithosh** [comment]
You can run a generic bootnode such as this one: https://github.com/protolambda/eth2-bootnode

The generic bootnode ENR can then be used.
