### ISSUE TITLE
CL_TIMESTAMP variable missing in values.env

### ISSUE THREAD

**Issue by samlaf** [ethpandaops/ethereum-genesis-generator#26]
`config.yaml` is expecting [CL_TIMESTAMP]( https://github.com/ethpandaops/ethereum-genesis-generator/blob/8893ad778cd3717be658778c8e93728c939831e1/config-example/cl/config.yaml#LL11C23-L11C23) variable which is not present in the [values.env](https://github.com/ethpandaops/ethereum-genesis-generator/blob/8893ad778cd3717be658778c8e93728c939831e1/config-example/values.env) file.

Am I supposed to add it? And is it supposed to be the same as GENESIS_TIMESTAMP?

**Comment by samlaf** [comment]
Actually it seems like the CL_TIMESTAMP is needed but not used. the `config.yaml` file that is generated has MIN_GENESIS_TIME set not to $CL_TIMESTAMP but actually to $GENESIS_TIMESTAMP (probably to stay in sync with the genesis.json generated for EL?)

**Comment by parithosh** [comment]
good catch, thanks! I'll set it to `$GENESIS_TIMESTAMP` to make it more standard. Fixed in commit `06d1cc9` already on master.
