### ISSUE TITLE
issue with decoding the eth1 config 

### ISSUE THREAD

**Issue by avenbreaks** [ethpandaops/ethereum-genesis-generator#39]
issue with decoding the eth1 config file in the Go code. it seems that this number is being interpreted as the value for the `cancunTime` field of type uint64 in the ChainConfig struct.

```
zrnt version: v0.30.0
failed to decode eth1 config file: json: cannot unmarshal number 7083549724304467820220 into Go struct field ChainConfig.config.cancunTime of type uint64
```

**Comment by parithosh** [comment]
That would happen if the default value for 4844(https://github.com/ethpandaops/ethereum-genesis-generator/blob/master/config-example/values.env#L13) is too high. It basically overflows when setting the timestamp for cancun. 
You can set it to a realistic(yet never reaching) number like epoch 99,000 or something.
